### ISSUE TITLE
Model Release ETA

### ISSUE THREAD

**Issue by Njasa2k** [VectorSpaceLab/OmniGen#1]
I'm excited about the OmniGen project and its potential for unified image generation. I was wondering if you could provide an estimated timeline for the model release?

Specifically, I'd love to know:

- Is there a rough ETA for the model release?
- Will there be any intermediate releases or previews before the full model is available?
- Are there any specific dependencies or milestones that need to be met before the model can be shared?

**Comment by madrooky** [comment]
By what I read in the paper:

- Nein
- Nein
- Nein

**Comment by ipepe** [comment]
> By what I read in the paper:
> 
> * Nein
> * Nein
> * Nein

Are you sure that's not part of the lyrics in the Du hast by Rammstein?

**Comment by staoxiao** [comment]
@ninjasaid2k, thank you for your attention to our work. We will release the model in October. 
Currently, we are trying to improve the quality of the generated images further.

**Comment by codingdudecom** [comment]
any clues as to the hw requirements (gpu vram etc) for this so that we can prepare :D ?

**Comment by ezorita** [comment]
> any clues as to the hw requirements (gpu vram etc) for this so that we can prepare :D ?

Only mention in the paper is that training was performed on 104 A800 (not specified if 40 or 80GB model) GPUs.

**Comment by JorgeR81** [comment]
> any clues as to the hw requirements (gpu vram etc) for this so that we can prepare :D ?

And, if it's too large for mid-tier consumer GPU, would a GGUF version work ?

**Comment by NielsRogge** [comment]
Subscribing to this thread, happy to help making the models available on HF, and linking them to https://huggingface.co/papers/2409.11340.

**Comment by martjay** [comment]
我为中国能做出一个能跟flux一较高下的模型感到骄傲，希望你们能做好它，我相信你们能做好

**Comment by staoxiao** [comment]
> 我为中国能做出一个能跟flux一较高下的模型感到骄傲，希望你们能做好它，我相信你们能做好

Thanks! We'll keep working on improving the model.  However, it needs to be clarified that due to limitations in data and computing resources, the current Omnigen can't achieve the same image quality as Flux. Omnigen is an exploration into general image generation, and we hope it inspires more simple and general diffusion models that are easier for users to use.

**Comment by fluthru** [comment]
For the love of God, release this already. I'm dying in anticipation to try it out! :)

**Comment by TruthSearcher** [comment]
@staoxiao is there any update on the release?

**Comment by NatanFreeman** [comment]
> @staoxiao is there any update on the release?

Yes, please see #6 one of the authors commented

**Comment by staoxiao** [comment]
Hi, everyone. Apologies for the late release of the model. We have updated the model and code, and we welcome you to explore OmniGen's features. Your feedback is also welcome to help us continue optimizing.

**Comment by JorgeR81** [comment]
Thanks for all your work !

Consider realizing also safetensers version. 

![sf](https://github.com/user-attachments/assets/713d24f9-580e-4e8a-96be-3f96a84bc64e)

**Comment by NielsRogge** [comment]
@JorgeR81 fair point. @staoxiao I see you leverage the `Phi3Model` model available in the Transformers library.

This means that you can push the Phi3 weights directly to the hub as follows:

```python
from OmniGen.transformer import Phi3Transformer

# load weights from .pt file
model = Phi3Transformer.from_pretrained("Shitao/OmniGen-v1")

# push to the hub (which will use safetensors by default)
model.push_to_hub("Shitao/OmniGen-v1")
```
Since [push_to_hub](https://huggingface.co/docs/transformers/v4.45.2/en/main_classes/model#transformers.PreTrainedModel.push_to_hub) uses `safetensors` by default.

**Comment by staoxiao** [comment]
@NielsRogge , thank you for your suggestion! However, OmniGen includes some additional parameters besides phi3, so directly using the Phi3Model might not work. We will try to optimize this storage format.

**Comment by aikitoria** [comment]
What caused the model to be marked as "suspicious" on HF?

**Comment by NielsRogge** [comment]
>  What caused the model to be marked as "suspicious" on HF?

It's a new feature on the hub, in collaboration with https://protectai.com/. Pickle is considered unsafe, see [this video](https://youtu.be/2ethDz9KnLk?si=dhYTayucdAoSyPiP) for an explainer.

**Comment by aikitoria** [comment]
No, pickle files can be safe if they have no imports. Here is an example: https://huggingface.co/CompVis/stable-diffusion-v1-4/tree/main/unet

So there has to be something peculiar about this one that it doesn't like. Unfortunately, it does not tell us what.

**Comment by fluthru** [comment]
How do you run this? I followed the few lines of instructions in the Quick Start section, but when I try to run app.py I get this error:

Traceback (most recent call last):
  File "\OmniGen\app.py", line 4, in <module>
    import spaces
ModuleNotFoundError: No module named 'spaces'

**Comment by aikitoria** [comment]
Hmm. It seems it's just complaining about these imports:

```
"torch.Tensor",
"torch._tensor._rebuild_from_type_v2",
```

**Comment by staoxiao** [comment]
> How do you run this? I followed the few lines of instructions in the Quick Start section, but when I try to run app.py I get this error:
> 
> Traceback (most recent call last): File "\OmniGen\app.py", line 4, in import spaces ModuleNotFoundError: No module named 'spaces'

For gradio app, some additional package is needed: `pip install gradio spaces`

**Comment by staoxiao** [comment]
@aikitoria @NielsRogge @JorgeR81 , we have converted the model into safetensors format, and the issue in HF is solved. Thanks for your suggestion!
