### ISSUE TITLE
App.py 229: SyntaxWarning: invalid escape sequence '\/'  

### ISSUE THREAD

**Issue by CWJ08** [VectorSpaceLab/OmniGen#111]
Hello, I'm having an issue running the OmniGen gui. I keep getting the error below when trying to run the command python app.py in the conda environment. Any help would be appreciated. More details below:

(omnigen) C:\OmniGen>python app.py
C:\OmniGen\app.py:229: SyntaxWarning: invalid escape sequence '\/'
  "<img><|image_1|><\/img> What item can be used to see the current time? Please highlight it in blue.",
C:\OmniGen\app.py:271: SyntaxWarning: invalid escape sequence '\<'
  description = """
Traceback (most recent call last):
  File "C:\OmniGen\app.py", line 9, in <module>
    from OmniGen import OmniGenPipeline
  File "C:\OmniGen\__init__.py", line 1, in <module>
    from .model import OmniGen
  File "C:\OmniGen\model.py", line 3, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

**Comment by able2608** [comment]
The syntax warning can be safely ignored, as it is talking about the escape sequence in the default examples, which does not seem to cause any problem except the warning. 
For the error you're encountering, it seem that a necessary library `torch` (a.k.a. pytorch) is not installed or not installed properly.  You might want to check if you have followed the installation guide carefully and did not omit any steps during the installation, which should have installed pytorch for you. If you want to use conda for your pytorch installation, you might want to run the following command to get the version required for OmniGen: 
`conda install pytorch==2.3.1 torchvision==0.18.1 pytorch-cuda=11.8 -c pytorch -c nvidia`

As a side note, if you are still getting `ModuleNotFoundError` after the installation of pytorch, you might need to rerun the last step of the installation script to make sure all the things that are needed are all installed:
`pip install -e .`
You might need to remove the first line `torch==2.3.1` in `requirements.txt` so that pip does not interfere with the previously installed pytorch version.
