### ISSUE TITLE
Issue trying to run app.py

### ISSUE THREAD

**Issue by Skettalee** [VectorSpaceLab/OmniGen#114]
Hello, i know I didn't follow your actually instructions but I did follow Youtuber Aitrepreneur from this video ( https://www.youtube.com/watch?v=aDKK2gXPIwE ) where he walked me through setting everything up and i think Im getting errors trying to create symbolic links as this console message says: 
Traceback (most recent call last):
  File "C:\!Sd\OmniGen\app.py", line 11, in <module>
    pipe = OmniGenPipeline.from_pretrained(
  File "C:\!Sd\OmniGen\OmniGen\pipeline.py", line 78, in from_pretrained
    model_name = snapshot_download(repo_id=model_name,
  File "C:\!Sd\OmniGen\env\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\!Sd\OmniGen\env\lib\site-packages\huggingface_hub\_snapshot_download.py", line 293, in snapshot_download
    thread_map(
  File "C:\!Sd\OmniGen\env\lib\site-packages\tqdm\contrib\concurrent.py", line 69, in thread_map
    return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "C:\!Sd\OmniGen\env\lib\site-packages\tqdm\contrib\concurrent.py", line 51, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
  File "C:\!Sd\OmniGen\env\lib\site-packages\tqdm\std.py", line 1181, in __iter__
    for obj in iterable:
  File "C:\Users\damie\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "C:\Users\damie\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "C:\Users\damie\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "C:\Users\damie\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\damie\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\!Sd\OmniGen\env\lib\site-packages\huggingface_hub\_snapshot_download.py", line 267, in _inner_hf_hub_download
    return hf_hub_download(
  File "C:\!Sd\OmniGen\env\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\!Sd\OmniGen\env\lib\site-packages\huggingface_hub\file_download.py", line 862, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "C:\!Sd\OmniGen\env\lib\site-packages\huggingface_hub\file_download.py", line 1022, in _hf_hub_download_to_cache_dir
    _create_symlink(blob_path, pointer_path, new_blob=True)
  File "C:\!Sd\OmniGen\env\lib\site-packages\huggingface_hub\file_download.py", line 586, in _create_symlink
    os.symlink(src_rel_or_abs, abs_dst)
OSError: [WinError 1314] A required privilege is not held by the client: '..\\..\\blobs\\6669392316dc8137610dc3d52536a5fefd94b6e5' -> 'C:\\Users\\damie\\.cache\\huggingface\\hub\\models--Shitao--OmniGen-v1\\snapshots\\58e249c7c7634423c0ba41c34a774af79aa87889\\README.md'

And if you want the complete log for that you can see it all here: https://pastebin.com/LHbtP7hU

**Comment by cassiebug23** [comment]
having the same issue.

**Comment by Skettalee** [comment]
It finally runs but there must be some problems because it is NOT doing any generating of images after it done the first one. I got it loaded again after having to completely close it and start it back up in hopes that it will generate an image but as of right now it has been going for 4 minutes and 22 seconds now showing nothing but this in the console : 
(env) C:\!Sd\OmniGen>python app.py
Fetching 10 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<?, ?it/s]
Loading safetensors
INFO: Could not find files for the given pattern(s).
* Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
C:\!Sd\OmniGen\env\lib\site-packages\diffusers\models\attention_processor.py:2358: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
  2%|▊                                     | 1/50 [01:43<1:24:35, 103.58s/it]
  hidden_states = F.scaled_dot_product_attention(
  0%|                                                 | 0/50 [00:00<?, ?it/s]
and it is not climbing at all. 
What did i do wrong that it wont work at all?
<edit> after 10 minutes it finally went up to 6% but this will get me nowhere very fast. Its not even worth trying to use this thing, can anyone give me some insights?

**Comment by staoxiao** [comment]
Hi, @Skettalee ， which GPU are you using? I suspect that the GPU might not be used, or CUDA might not be compatible with your version of Torch.

**Comment by nitinmukesh** [comment]
@Skettalee @cassiebug23 

The video you shared is already removed by Youtube.

See if this works
https://youtu.be/9ZXmXA2AJZ4?si=M2kESfsCh-LO-5Ky

**Comment by Skettalee** [comment]
> @Skettalee @cassiebug23
> 
> The video you shared is already removed by Youtube.
> 
> See if this works https://youtu.be/9ZXmXA2AJZ4?si=M2kESfsCh-LO-5Ky

Yeah that video still works just fine, does it not pull up for you?

**Comment by Skettalee** [comment]
> Hi, @Skettalee ， which GPU are you using? I suspect that the GPU might not be used, or CUDA might not be compatible with your version of Torch.

I have an Nvidia rtx 4070 with cues 12.1 installed. I had installed the PyTorch with cu121 also in the env

**Comment by nitinmukesh** [comment]
> Hello, i know I didn't follow your actually instructions but I did follow Youtuber Aitrepreneur from this video ( https://www.youtube.com/watch?v=aDKK2gXPIwE ) where he walked me through setting everything up and i think Im getting errors trying to create symbolic links as this console message says: Traceback (most recent call last): 

![image](https://github.com/user-attachments/assets/edb24255-f8a7-4e41-a29c-e34d6c367039)

**Comment by Skettalee** [comment]
Yep your right, I clicked the link on my phone and it still worked but tried in computer and was gone then came to phone and now gone there

**Comment by nitinmukesh** [comment]
@Skettalee 

Just check if the link I provided work. Several users reported it working fine on their machine.

**Comment by Skettalee** [comment]
What link you provided? I see no links

**Comment by nitinmukesh** [comment]
> What link you provided? I see no links

https://youtu.be/9ZXmXA2AJZ4?si=M2kESfsCh-LO-5Ky

**Comment by Skettalee** [comment]
The YouTuber reuploaded his video through rumble if you want to see it, it’s here : 
https://rumble.com/v5ns1i5-uncensored-new-ai-tool-create-nsfw-images-now.html

**Comment by Skettalee** [comment]
> > What link you provided? I see no links
> 
> https://youtu.be/9ZXmXA2AJZ4?si=M2kESfsCh-LO-5Ky

Ok now I understand, I will have to watch this one later on, thanks for posting it. I’ll reply back once I see it.

**Comment by able2608** [comment]
@Skettalee Try turning off `offload_model` or `separate_cfg_infer` so that you are not using system RAM (or swap files). Monitor whether your GPU does have activity when generating image. If you do not see the GPU doing anything, it might be that your pytorch installation is CPU only and you'll need to reinstall it with GPU support. 4070 definitely will give good performance if it is utilized properly.
