### ISSUE TITLE
Can't start train

### ISSUE THREAD

**Issue by shadovv76** [VectorSpaceLab/OmniGen#128]
accelerate launch --config_file "C:/Users/1/.cache/huggingface/accelerate/default_config.yaml" train.py --model_name_or_path Shitao/OmniGen-v1 --batch_size_per_device 1 --condition_dropout_prob 0.01 --lr 1e-3 --use_lora --lora_rank 8 --json_file ./toy_data/toy_subject_data.jsonl --image_path ./toy_data/images --max_input_length_limit 18000 --keep_raw_resolution --max_image_size 512 --gradient_accumulation_steps 1 --ckpt_every 10 --epochs 200 --log_every 1 --results_dir ./results/toy_finetune_lora
C:\Users\1\miniconda3\envs\omnigen\lib\site-packages\accelerate\accelerator.py:393: UserWarning: `log_with=tensorboard` was passed but no supported trackers are currently installed.
  warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.")
[2024-11-15 20:15:43] Experiment directory created at ./results/toy_finetune_lora
Fetching 10 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<?, ?it/s]
[2024-11-15 20:16:06] Downloaded model to C:\Users\1\.cache\huggingface\hub\models--Shitao--OmniGen-v1\snapshots\58e249c7c7634423c0ba41c34a774af79aa87889
Loading safetensors
[2024-11-15 20:17:01] Dataset contains 5
[2024-11-15 20:17:01] Training for 200 epochs...
[2024-11-15 20:17:01] Beginning epoch 0...
Traceback (most recent call last):
  File "c:\Users\1\Downloads\loras\omnigen\train.py", line 400, in <module>
    main(args)
  File "c:\Users\1\Downloads\loras\omnigen\train.py", line 197, in main
    for data in loader:
  File "C:\Users\1\miniconda3\envs\omnigen\lib\site-packages\accelerate\data_loader.py", line 448, in __iter__
    dataloader_iter = super().__iter__()
  File "C:\Users\Ceasar\miniconda3\envs\omnigen\lib\site-packages\torch\utils\data\dataloader.py", line 439, in __iter__
    return self._get_iterator()
  File "C:\Users\1\miniconda3\envs\omnigen\lib\site-packages\torch\utils\data\dataloader.py", line 387, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\1\miniconda3\envs\omnigen\lib\site-packages\torch\utils\data\dataloader.py", line 1040, in __init__
    w.start()
  File "C:\Users\1\miniconda3\envs\omnigen\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\1\miniconda3\envs\omnigen\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\1\miniconda3\envs\omnigen\lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
  File "C:\Users\1\miniconda3\envs\omnigen\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\1\miniconda3\envs\omnigen\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'main.<locals>.<lambda>'

Windows 10 
Python 3.10.15
One GPU(4090) no distribute.
Accelerate config:
compute_environment: LOCAL_MACHINE
debug: false
distributed_type: 'NO'
downcast_bf16: 'no'
gpu_ids: '0'
machine_rank: 0
main_training_function: main
mixed_precision: fp8
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false

**Comment by staoxiao** [comment]
Strange issue. @shadovv76 , you can try to set argument `--num_workers 1`

**Comment by shadovv76** [comment]
thank you, but the same error "main.<locals>.<lambda>"

accelerate launch --num_processes=1 train.py --num_workers 1 --model_name_or_path Shitao/OmniGen-v1 --batch_size_per_device 2 --condition_dropout_prob 0.01 --lr 1e-3 --use_lora --lora_rank 8 --json_file ./toy_data/toy_subject_data.jsonl --image_path ./toy_data/images --max_input_length_limit 18000 --keep_raw_resolution --max_image_size 1024 --gradient_accumulation_steps 1 --ckpt_every 10 --epochs 200 --log_every 1 --results_dir ./results/toy_finetune_lora
C:\Users\1\miniconda3\envs\omnigen\lib\site-packages\accelerate\accelerator.py:393: UserWarning: `log_with=tensorboard` was passed but no supported trackers are currently installed.
  warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.")
[2024-11-16 14:09:33] Experiment directory created at ./results/toy_finetune_lora
Fetching 10 files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<?, ?it/s]
[2024-11-16 14:09:33] Downloaded model to C:\Users\1\.cache\huggingface\hub\models--Shitao--OmniGen-v1\snapshots\58e249c7c7634423c0ba41c34a774af79aa87889
Loading safetensors
[2024-11-16 14:10:15] Dataset contains 5
[2024-11-16 14:10:15] Training for 200 epochs...
[2024-11-16 14:10:15] Beginning epoch 0...
Traceback (most recent call last):
  File "c:\Users\1\Downloads\loras\omnigen\train.py", line 398, in <module>
    main(args)
  File "c:\Users\1\Downloads\loras\omnigen\train.py", line 195, in main
    for data in loader:
  File "C:\Users\1\miniconda3\envs\omnigen\lib\site-packages\accelerate\data_loader.py", line 448, in __iter__
    dataloader_iter = super().__iter__()
  File "C:\Users\1\miniconda3\envs\omnigen\lib\site-packages\torch\utils\data\dataloader.py", line 439, in __iter__
    return self._get_iterator()
  File "C:\Users\1\miniconda3\envs\omnigen\lib\site-packages\torch\utils\data\dataloader.py", line 387, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\1\miniconda3\envs\omnigen\lib\site-packages\torch\utils\data\dataloader.py", line 1040, in __init__
    w.start()
  File "C:\Users\1\miniconda3\envs\omnigen\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\1\miniconda3\envs\omnigen\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\1\miniconda3\envs\omnigen\lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
  File "C:\Users\1\miniconda3\envs\omnigen\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\1\miniconda3\envs\omnigen\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'main.<locals>.<lambda>'

**Comment by shadovv76** [comment]
is it be right in toy_subject_data.json  "text_to_iamge" not IMage?

**Comment by shadovv76** [comment]
jupyter was not instaled. I had instaled it, but error the same. (and without num_workers key too)


pip show transformers datasets accelerate jupyter pillow peft diffusers timm
Name: transformers
Version: 4.45.2
Summary: State-of-the-art Machine Learning for JAX, PyTorch and TensorFlow
Home-page: https://github.com/huggingface/transformers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/transformers/graphs/contributors)
Author-email: transformers@huggingface.co
License: Apache 2.0 License
Location: c:\users\1\miniconda3\envs\omnigen\lib\site-packages
Requires: filelock, huggingface-hub, numpy, packaging, pyyaml, regex, requests, safetensors, tokenizers, tqdm
Required-by: peft
---
Name: datasets
Version: 2.20.0
Summary: HuggingFace community-driven open-source library of datasets
Home-page: https://github.com/huggingface/datasets
Author: HuggingFace Inc.
Author-email: thomas@huggingface.co
License: Apache 2.0
Location: c:\users\1\miniconda3\envs\omnigen\lib\site-packages
Requires: aiohttp, dill, filelock, fsspec, huggingface-hub, multiprocess, numpy, packaging, pandas, pyarrow, pyarrow-hotfix, pyyaml, requests, tqdm, xxhash
Required-by:
---
Name: accelerate
Version: 0.26.1
Summary: Accelerate
Home-page: https://github.com/huggingface/accelerate
Author: The HuggingFace team
Author-email: sylvain@huggingface.co
License: Apache
Location: c:\users\1\miniconda3\envs\omnigen\lib\site-packages
Requires: huggingface-hub, numpy, packaging, psutil, pyyaml, safetensors, torch
Required-by: peft
---
Name: jupyter
Version: 1.0.0
Summary: Jupyter metapackage. Install all the Jupyter components in one go.
Home-page: http://jupyter.org
Author: Jupyter Development Team
Author-email: jupyter@googlegroups.org
License: BSD
Location: c:\users\1\miniconda3\envs\omnigen\lib\site-packages
Requires: ipykernel, ipywidgets, jupyter-console, nbconvert, notebook, qtconsole
Required-by:
---
Name: pillow
Version: 10.2.0
Summary: Python Imaging Library (Fork)
Home-page: https://python-pillow.org
Author:
Author-email: "Jeffrey A. Clark (Alex)" <aclark@aclark.net>
License: HPND
Location: c:\users\1\miniconda3\envs\omnigen\lib\site-packages
Requires:
Required-by: diffusers, gradio, torchvision
---
Name: peft
Version: 0.13.2
Summary: Parameter-Efficient Fine-Tuning (PEFT)
Home-page: https://github.com/huggingface/peft
Author: The HuggingFace team
Author-email: benjamin@huggingface.co
License: Apache
Location: c:\users\1\miniconda3\envs\omnigen\lib\site-packages
Requires: accelerate, huggingface-hub, numpy, packaging, psutil, pyyaml, safetensors, torch, tqdm, transformers
Required-by:
---
Name: diffusers
Version: 0.30.3
Summary: State-of-the-art diffusion in PyTorch and JAX.
Home-page: https://github.com/huggingface/diffusers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/diffusers/graphs/contributors)
Author-email: diffusers@huggingface.co
License: Apache 2.0 License
Location: c:\users\1\miniconda3\envs\omnigen\lib\site-packages
Requires: filelock, huggingface-hub, importlib-metadata, numpy, Pillow, regex, requests, safetensors
Required-by:
---
Name: timm
Version: 0.9.16
Summary: PyTorch Image Models
Home-page: https://github.com/huggingface/pytorch-image-models
Author:
Author-email: Ross Wightman <ross@huggingface.co>
License: Apache-2.0
Location: c:\users\1\miniconda3\envs\omnigen\lib\site-packages
Requires: huggingface_hub, pyyaml, safetensors, torch, torchvision
Required-by

pip show numpy
Name: numpy
Version: 1.26.3

**Comment by Nazzaroth2** [comment]
I had a similar issue. I resolved it by setting --num_workers to 0 and adjusting the dataloader in train.py

comment out or remove the prefetch_factor.
  loader = DataLoader(
      dataset,
      collate_fn=collate_fn,
      batch_size=args.batch_size_per_device,
      shuffle=True,
      num_workers=args.num_workers,
      pin_memory=True,
      drop_last=True,
      # prefetch_factor=2,
  )

I am assuming this has a slight performance hit as this will create a small dataloading bottleneck but atleast you can use the scripts on windows that way.

**Comment by shadovv76** [comment]
It is live!
[Nazzaroth2](https://github.com/Nazzaroth2), very big thanks for you!
