### ISSUE TITLE
can this run on a 3080 card? i keep getting errors

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [VectorSpaceLab/OmniGen#146]
Please I keep getting this error:

I have a 3080, on windows 11.
is this sufficient to run the app?

<img width="515" alt="image" src="https://github.com/user-attachments/assets/bccfa8f6-e634-43f5-b11e-70d636de10fc">

```
Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\envs\omnigen\lib\site-packages\gradio\queueing.py", line 624, in process_events
    response = await route_utils.call_process_api(
  File "C:\ProgramData\miniconda3\envs\omnigen\lib\site-packages\gradio\route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\ProgramData\miniconda3\envs\omnigen\lib\site-packages\gradio\blocks.py", line 2015, in process_api
    result = await self.call_function(
  File "C:\ProgramData\miniconda3\envs\omnigen\lib\site-packages\gradio\blocks.py", line 1562, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\ProgramData\miniconda3\envs\omnigen\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\ProgramData\miniconda3\envs\omnigen\lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "C:\ProgramData\miniconda3\envs\omnigen\lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "C:\ProgramData\miniconda3\envs\omnigen\lib\site-packages\gradio\utils.py", line 865, in wrapper
    response = f(*args, **kwargs)
  File "D:\OmniGen\app.py", line 27, in generate_image
    output = pipe(
  File "C:\ProgramData\miniconda3\envs\omnigen\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "D:\OmniGen\OmniGen\pipeline.py", line 284, in __call__
    samples = scheduler(latents, func, model_kwargs, use_kv_cache=use_kv_cache, offload_kv_cache=offload_kv_cache)
  File "D:\OmniGen\OmniGen\scheduler.py", line 158, in __call__
    cache = [OmniGenCache(num_tokens_for_img, offload_kv_cache) for _ in range(len(model_kwargs['input_ids']))] if use_kv_cache else None
  File "D:\OmniGen\OmniGen\scheduler.py", line 158, in <listcomp>
    cache = [OmniGenCache(num_tokens_for_img, offload_kv_cache) for _ in range(len(model_kwargs['input_ids']))] if use_kv_cache else None
  File "D:\OmniGen\OmniGen\scheduler.py", line 16, in __init__
    raise RuntimeError("OffloadedCache can only be used with a GPU. If there is no GPU, you need to set use_kv_cache=False, which will result in longer inference time!")
RuntimeError: OffloadedCache can only be used with a GPU. If there is no GPU, you need to set use_kv_cache=False, which will result in longer inference time!
```

**Comment by staoxiao** [comment]
@CharlesOkwuagwu, this issue is because you haven't properly installed Torch. You can refer to the following command to install it: `pip install torch==2.3.1+cu118 torchvision --extra-index-url https://download.pytorch.org/whl/cu118
`

**Comment by CharlesOkwuagwu** [comment]
> @CharlesOkwuagwu, this issue is because you haven't properly installed Torch. You can refer to the following command to install it: `pip install torch==2.3.1+cu118 torchvision --extra-index-url https://download.pytorch.org/whl/cu118 `

works now

**Comment by Jun-Pal** [comment]
I got the same error with the **1070ti** card. please help me.
![image](https://github.com/user-attachments/assets/f3a46b6a-8109-4911-9769-f9a35215b773)

**Comment by CharlesOkwuagwu** [comment]
> I got the same error with the **1070ti** card. please help me. ![image](https://private-user-images.githubusercontent.com/173559697/391336615-f3a46b6a-8109-4911-9769-f9a35215b773.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNjE2MDUsIm5iZiI6MTczMzA2MTMwNSwicGF0aCI6Ii8xNzM1NTk2OTcvMzkxMzM2NjE1LWYzYTQ2YjZhLTgxMDktNDkxMS05NzY5LWY5YTM1MjE1Yjc3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMVQxMzU1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZWM0NDAwYTJkNTY4YmQ0YjgwMzdlZjk1MGYzZmIzZDdjMTZjZWExYzhiZTc3ZmU5NjI1YWRhOGQzOGQyNTU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vdmLMjPVK4feb4zpTjuGTAmf6SMnRb0776T8LKrAYCg)


I think it needs the exact: 
pip install torch==2.3.1+cu118 torchvision --extra-index-url https://download.pytorch.org/whl/cu118 

I put this in a new conda environment, and it worked.

**Comment by nitinmukesh** [comment]
@Jun-Pal 

See if this guide helps
https://youtu.be/9ZXmXA2AJZ4
