### ISSUE TITLE
After the installation is completed, the http://127.0.0.1:7860/ page cannot be opened.

### ISSUE THREAD

**Issue by tangA008** [VectorSpaceLab/OmniGen#153]
F:\OmniGen>python app.py
Fetching 10 files: 100%|███████████████████████████████████████████████████████████████████████| 10/10 [00:00<?, ?it/s]
Loading safetensors
Running on local URL:  http://127.0.0.1:7860
C:\Users\YC-02\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\analytics.py:106: UserWarning: IMPORTANT: You are using gradio version 4.41.0, however version 4.44.1 is available, please upgrade.
--------
  warnings.warn(
Traceback (most recent call last):
  File "F:\OmniGen\app.py", line 431, in <module>
    demo.launch(share=args.share)
  File "C:\Users\YC-02\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 2456, in launch
    raise ValueError(
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.

F:\OmniGen>

**Comment by able2608** [comment]
Perhaps there are network configurations preventing the access to localhost. You might want to check out this issue to troubleshoot your problem: https://github.com/gradio-app/gradio/issues/4046.
