### ISSUE TITLE
can't run the UI

### ISSUE THREAD

**Issue by ganzon** [VectorSpaceLab/OmniGen#157]
After this command "python app.py" the following message show up.

```
D:\AI\OmniGen\app.py:229: SyntaxWarning: invalid escape sequence '\/'
  "<img><|image_1|><\/img> What item can be used to see the current time? Please highlight it in blue.",
D:\AI\OmniGen\app.py:271: SyntaxWarning: invalid escape sequence '\<'
  description = """
Traceback (most recent call last):
  File "D:\AI\OmniGen\app.py", line 9, in <module>
    from OmniGen import OmniGenPipeline
  File "D:\AI\OmniGen\OmniGen\__init__.py", line 1, in <module>
    from .model import OmniGen
  File "D:\AI\OmniGen\OmniGen\model.py", line 3, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

```

**Comment by able2608** [comment]
Please follow the instructions provided below (in the `README.md` file) and install all required libraries before running the demo. The error you get simply means that the required library `torch` is not installed or not installed properly. If you have follow the installation instructions before, please uninstall `torch` (via `pip` or `conda`, depending on how you did it) and reinstall it again to fix improper installation.
https://github.com/VectorSpaceLab/OmniGen?tab=readme-ov-file#5-quick-start

**Comment by ganzon** [comment]
After follow the exact step in the link provided, after I enter "python app.py" this is showing

```
Traceback (most recent call last):
  File "D:\AI\OmniGen\app.py", line 9, in <module>
    from OmniGen import OmniGenPipeline
  File "D:\AI\OmniGen\OmniGen\__init__.py", line 1, in <module>
    from .model import OmniGen
  File "D:\AI\OmniGen\OmniGen\model.py", line 9, in <module>
    from diffusers.loaders import PeftAdapterMixin
ModuleNotFoundError: No module named 'diffusers'

```

**Comment by puzzlehead4811** [comment]
> I deleted the wold Omnigen, and did all over again step by step. After follow the exact step in the link provided, after I enter "python app.py" this is showing
> 
> ```
> Traceback (most recent call last):
>   File "D:\AI\OmniGen\app.py", line 9, in <module>
>     from OmniGen import OmniGenPipeline
>   File "D:\AI\OmniGen\OmniGen\__init__.py", line 1, in <module>
>     from .model import OmniGen
>   File "D:\AI\OmniGen\OmniGen\model.py", line 9, in <module>
>     from diffusers.loaders import PeftAdapterMixin
> ModuleNotFoundError: No module named 'diffusers'
> ```

I have the same issue did you manage to solve it?

**Comment by cleverestx** [comment]
> I deleted the wold Omnigen, and did all over again step by step. After follow the exact step in the link provided, after I enter "python app.py" this is showing
> 
> ```
> Traceback (most recent call last):
>   File "D:\AI\OmniGen\app.py", line 9, in <module>
>     from OmniGen import OmniGenPipeline
>   File "D:\AI\OmniGen\OmniGen\__init__.py", line 1, in <module>
>     from .model import OmniGen
>   File "D:\AI\OmniGen\OmniGen\model.py", line 9, in <module>
>     from diffusers.loaders import PeftAdapterMixin
> ModuleNotFoundError: No module named 'diffusers'
> ```

Same with me now. How did you resolve this?

**Comment by cleverestx** [comment]
Nevermind.  I ran:  pip install -r requirements. txt  in my conda instance - it appears to be loading the models now...

This resolved it for me. I thought I had done this before, but I guess I missed it.
