### ISSUE TITLE
How to finetune for image inpainting and outpainting ?

### ISSUE THREAD

**Issue by thesby** [VectorSpaceLab/OmniGen#20]

**Comment by staoxiao** [comment]
You can refer to https://github.com/VectorSpaceLab/OmniGen/blob/main/docs/fine-tuning.md
When preparing the data for training, you can add a mask (a black area) to the original image as the input image and use the original image as the output. During inference, input an image with the mask.

**Comment by win10ogod** [comment]
> You can refer to https://github.com/VectorSpaceLab/OmniGen/blob/main/docs/fine-tuning.md When preparing the data for training, you can add a mask (a black area) to the original image as the input image and use the original image as the output. During inference, input an image with the mask.
@staoxiao Please fix the bug on windows!
```
Traceback (most recent call last):
  File "E:\OmniGen\train.py", line 371, in <module>
    main(args)
  File "E:\OmniGen\train.py", line 197, in main
    for data in loader:
  File "C:\Users\jmes1\AppData\Local\Programs\Python\Python311\Lib\site-packages\accelerate\data_loader.py", line 448, in __iter__
    dataloader_iter = super().__iter__()
                      ^^^^^^^^^^^^^^^^^^
  File "C:\Users\jmes1\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\data\dataloader.py", line 440, in __iter__
    return self._get_iterator()
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jmes1\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\data\dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jmes1\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\data\dataloader.py", line 1038, in __init__
    w.start()
  File "C:\Users\jmes1\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\jmes1\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jmes1\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\jmes1\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\popen_spawn_win32.py", line 95, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\jmes1\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'main.<locals>.<lambda>'
```

**Comment by mapengsen** [comment]
May I ask what the proportion of the picture with mask should be? 
Should I train another inpainting model?
