### ISSUE TITLE
D:\OmniGen\app.py:138: SyntaxWarning: invalid escape sequence '\/'

### ISSUE THREAD

**Issue by Cokeheart** [VectorSpaceLab/OmniGen#33]
Successfully installed aiofiles-23.2.1 annotated-types-0.7.0 anyio-4.6.2.post1 certifi-2024.8.30 charset-normalizer-3.4.0 click-8.1.7 colorama-0.4.6 fastapi-0.115.3 ffmpy-0.4.0 gradio-5.3.0 gradio-client-1.4.2 httpcore-1.0.6 httpx-0.27.2 huggingface-hub-0.26.1 jinja2-3.1.4 markdown-it-py-3.0.0 markupsafe-2.1.5 mdurl-0.1.2 orjson-3.10.10 pandas-2.2.3 pydantic-2.9.2 pydantic-core-2.23.4 pygments-2.18.0 python-multipart-0.0.14 requests-2.32.3 rich-13.9.3 starlette-0.41.1 tqdm-4.66.5 typer-0.12.5 uvicorn-0.32.0

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

D:\OmniGen>python app.py
D:\OmniGen\app.py:138: SyntaxWarning: invalid escape sequence '\/'
  "<img><|image_1|><\/img> What item can be used to see the current time? Please remove it.",
D:\OmniGen\app.py:149: SyntaxWarning: invalid escape sequence '\/'
  "Three guitars are displayed side by side on a rustic wooden stage, each showcasing its unique character and style. The left guitar is <img><|image_1|><\/img>. The middle guitar is <img><|image_2|><\/img>. The right guitars is <img><|image_3|><\/img>.",
D:\OmniGen\app.py:165: SyntaxWarning: invalid escape sequence '\<'
  description = """
Traceback (most recent call last):
  File "D:\OmniGen\app.py", line 1, in <module>
    import gradio as gr
  File "C:\Users\josep\Python\Python312\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "C:\Users\josep\Python\Python312\site-packages\gradio\_simple_templates\__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "C:\Users\josep\Python\Python312\site-packages\gradio\_simple_templates\simpledropdown.py", line 7, in <module>
    from gradio.components.base import Component, FormComponent
  File "C:\Users\josep\Python\Python312\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "C:\Users\josep\Python\Python312\site-packages\gradio\components\annotated_image.py", line 14, in <module>
    from gradio import processing_utils, utils
  File "C:\Users\josep\Python\Python312\site-packages\gradio\processing_utils.py", line 34, in <module>
    from gradio.route_utils import API_PREFIX
  File "C:\Users\josep\Python\Python312\site-packages\gradio\route_utils.py", line 34, in <module>
    import multipart
ModuleNotFoundError: No module named 'multipart'

**Comment by staoxiao** [comment]
I'm not sure about the purpose of this package either; you can try installing it manually: `pip install multipart`

**Comment by pluberd** [comment]
./OmniGen$ python ./app.py
./OmniGen/./app.py:142: SyntaxWarning: invalid escape sequence '\/'
  "The flower <img><|image_1|><\/img> is placed in the vase which is in the middle of <img><|image_2|><\/img> on a wooden table of a living room",
./OmniGen/./app.py:238: SyntaxWarning: invalid escape sequence '\/'
  "<img><|image_1|><\/img> What item can be used to see the current time? Please remove it.",
./OmniGen/./app.py:277: SyntaxWarning: invalid escape sequence '\<'
  description = """
