### ISSUE TITLE
Errors when running on Macos Sonoma - M1 RuntimeError: OffloadedCache can only be used with a GPU

### ISSUE THREAD

**Issue by adamreading** [VectorSpaceLab/OmniGen#55]
M1 Silicon Macos - 16Gb Ram - Sonoma 14.6.1 (23G93)
Installed with Pinokio
No obvious Install errors (zip attached)

 I have tried every combination of checkboxes and I always get the same error that RuntimeError: OffloadedCache can only be used with a GPU, no matter what that is set to.

######################################################################
#
# group: /Users/Shared/pinokio/api/omnigen.git/start.js
# id: 5a382145-df88-445b-a9f4-55a2a2dc5ca9
# index: 1
[newlogs.zip](https://github.com/user-attachments/files/17561436/newlogs.zip)

# cmd: eval "$(conda shell.bash hook)" && conda deactivate && conda deactivate && conda deactivate && conda activate base && source /Users/Shared/pinokio/api/omnigen.git/app/env/bin/activate /Users/Shared/pinokio/api/omnigen.git/app/env && python app.py
# timestamp: 10/29/2024, 6:12:23 PM (1730225543006)

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
<<PINOKIO_SHELL>>eval "$(conda shell.bash hook)" && conda deactivate && conda deactivate && conda deactivate && conda activate base && source /Users/Shared/pinokio/api/omnigen.git/app/env/bin/activate /Users/Shared/pinokio/api/omnigen.git/app/env && python app.py
Fetching 10 files: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 10/10 [00:00<00:00, 61771.78it/s]
Loading safetensors
* Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/Users/Shared/pinokio/api/omnigen.git/app/env/lib/python3.10/site-packages/gradio/queueing.py", line 624, in process_events
    response = await route_utils.call_process_api(
  File "/Users/Shared/pinokio/api/omnigen.git/app/env/lib/python3.10/site-packages/gradio/route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
  File "/Users/Shared/pinokio/api/omnigen.git/app/env/lib/python3.10/site-packages/gradio/blocks.py", line 2018, in process_api
    result = await self.call_function(
  File "/Users/Shared/pinokio/api/omnigen.git/app/env/lib/python3.10/site-packages/gradio/blocks.py", line 1567, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/Users/Shared/pinokio/api/omnigen.git/app/env/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/Users/Shared/pinokio/api/omnigen.git/app/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "/Users/Shared/pinokio/api/omnigen.git/app/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "/Users/Shared/pinokio/api/omnigen.git/app/env/lib/python3.10/site-packages/gradio/utils.py", line 846, in wrapper
    response = f(*args, **kwargs)
  File "/Users/Shared/pinokio/api/omnigen.git/app/app.py", line 22, in generate_image
    output = pipe(
  File "/Users/Shared/pinokio/api/omnigen.git/app/env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/Shared/pinokio/api/omnigen.git/app/OmniGen/pipeline.py", line 280, in __call__
    samples = scheduler(latents, func, model_kwargs, use_kv_cache=use_kv_cache, offload_kv_cache=offload_kv_cache)
  File "/Users/Shared/pinokio/api/omnigen.git/app/OmniGen/scheduler.py", line 156, in __call__
    cache = [OmniGenCache(num_tokens_for_img, offload_kv_cache) for _ in range(len(model_kwargs['input_ids']))] if use_kv_cache else None
  File "/Users/Shared/pinokio/api/omnigen.git/app/OmniGen/scheduler.py", line 156, in <listcomp>
    cache = [OmniGenCache(num_tokens_for_img, offload_kv_cache) for _ in range(len(model_kwargs['input_ids']))] if use_kv_cache else None
  File "/Users/Shared/pinokio/api/omnigen.git/app/OmniGen/scheduler.py", line 14, in __init__
    raise RuntimeError("OffloadedCache can only be used with a GPU")
RuntimeError: OffloadedCache can only be used with a GPU

**Comment by staoxiao** [comment]
@adamreading , the current code doesn't support m1. I tried running it on a Mac with an M2 chip, and it was very slow. I don't recommend running OmniGen on it. It may require specific optimizations.

**Comment by adamreading** [comment]
I’ve seen it’s been released on comfyui node today when I get home I will try that in my cloud server

**Comment by yukiarimo** [comment]
Following

**Comment by yukiarimo** [comment]
The HF demo doesn't work

**Comment by fah** [comment]
@adamreading
> comfyui

You meant this?: https://github.com/AIFSH/OmniGen-ComfyUI

**Comment by sommersohn** [comment]
Gut the same errors here on my Macbook Air M1.

**Comment by adamreading** [comment]
> Having the same errors here on my Macbook Air M1.

I ended up running it on a cloud server - way faster and super easy to use - https://mimicpc.com/?fpr=adam47
