### ISSUE TITLE
NameError: name 'is_torch_npu_available' is not defined. Did you mean: 'is_torch_xla_available'?

### ISSUE THREAD

**Issue by fbauer-kunbus** [VectorSpaceLab/OmniGen#67]
When starting python app.py I get this error:

NameError: name 'is_torch_npu_available' is not defined. Did you mean: 'is_torch_xla_available'?

**Comment by RodgerE1** [comment]
SAME:

(omnigen_env) PS C:\OmniGen> python app.py
Fetching 10 files: 100%|███████████████████████████████████████████████████████████████████████| 10/10 [00:00<?, ?it/s]
Loading safetensors
Traceback (most recent call last):
  File "C:\OmniGen\app.py", line 9, in <module>
    pipe = OmniGenPipeline.from_pretrained(
  File "C:\OmniGen\OmniGen\pipeline.py", line 93, in from_pretrained
    return cls(vae, model, processor)
  File "C:\OmniGen\OmniGen\pipeline.py", line 61, in __init__
    elif is_torch_npu_available():
NameError: name 'is_torch_npu_available' is not defined. Did you mean: 'is_torch_xla_available'?
(omnigen_env) PS C:\OmniGen>

**Comment by fbauer-kunbus** [comment]
> Hi, @fbauer-kunbus @RodgerE1 , this is a bug, and I will fix it. However, this issue arises when your machine doesn't have a GPU and can only use the CPU for inference, which results in very slow generation speeds. We do not recommend using the CPU for inference.

No, this can't be it - I have a laptop 4090 with 16GB VRAM that is running all my AI apps succesfully for a long time, even in same cuda venv environments - never had this issue before.

**Comment by Bouhoum** [comment]
same here, I do have a gpu but still I get same error, I have a 4070

**Comment by staoxiao** [comment]
I updated the code. You can clone the latest code and try it.

**Comment by Bouhoum** [comment]
The first error has been solved, but still getting one

**Comment by fbauer-kunbus** [comment]
Same here ... After updating I now get over the original error - but when trying to create an image it now returns:

OffloadedCache can only be used with a GPU

But it doesn't look as if it is trying to use the GPU at all ...

**Comment by LeoRibkin** [comment]
same here

**Comment by MoRgllgRoM** [comment]
same here 
3080ti 12GB

**Comment by staoxiao** [comment]
The issue is that no GPU device is detected, i.e., `torch.cuda.is_available()=False`. This could be due to an environment issue, such as PyTorch not being installed, or a mismatch between the PyTorch and CUDA versions. If the torch version is not suitable for your device, you can use lower version, e.g., 2.1
You can print `torch.cuda.is_available()` in the same environment to check if the GPU is correctly recognized.

**Comment by staoxiao** [comment]
I modified the `setup.py` file to relax the version requirement for torch from `==2.3.1` to `<2.5` (because there is a bug in torch 2.5). This might help to construct a correct environment.

**Comment by fbauer-kunbus** [comment]
> I modified the `setup.py` file to relax the version requirement for torch from `==2.3.1` to `<2.5` (because there is a bug in torch 2.5). This might help to construct a correct environment.

did "git pull origin main" but it says "Already up to date"

So did you not put your setup.py into the main branch?

**Comment by staoxiao** [comment]
> > I modified the `setup.py` file to relax the version requirement for torch from `==2.3.1` to `<2.5` (because there is a bug in torch 2.5). This might help to construct a correct environment.
> 
> did "git pull origin main" but it says "Already up to date"
> 
> So did you not put your setup.py into the main branch?

Yeah, the modification have been merged: https://github.com/VectorSpaceLab/OmniGen/commit/5f9fe4a452753685abd472f469a087d6cf7a5792

**Comment by fbauer-kunbus** [comment]
> > > I modified the `setup.py` file to relax the version requirement for torch from `==2.3.1` to `<2.5` (because there is a bug in torch 2.5). This might help to construct a correct environment.
> > 
> > 
> > did "git pull origin main" but it says "Already up to date"
> > So did you not put your setup.py into the main branch?
> 
> Yeah, the modification have been merged: [5f9fe4a](https://github.com/VectorSpaceLab/OmniGen/commit/5f9fe4a452753685abd472f469a087d6cf7a5792)

so should pulling the main branch now work? I did, and files changed - but the error stays the same:

RuntimeError: OffloadedCache can only be used with a GPU

**Comment by w0ver** [comment]
okay i fixed this problem by runing 

conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia

and than 

$env:KMP_DUPLICATE_LIB_OK="TRUE"
 
 and than run the app.py and it work now.
 
 ---------------------------------------------------
(omnigen) PS S:\NEW\OmniGen> python -c "import torch; print(torch.cuda.is_available())"
False

(omnigen) PS S:\NEW\OmniGen> conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch
 -c nvidia
 
 Proceed ([y]/n)? y

Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(omnigen) PS S:\NEW\OmniGen> $env:KMP_DUPLICATE_LIB_OK="TRUE"

(omnigen) PS S:\NEW\OmniGen> python app.py

Fetching 10 files: 100%|█████████████████████████████████████████████████████| 10/10 [00:00<?, ?it/s]
Loading safetensors
INFO: Could not find files for the given pattern(s).
* Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
100%|████████████████████████████████████████████████████████████████| 50/50 [00:22<00:00,  2.21it/s]
100%|████████████████████████████████████████████████████████████████| 50/50 [00:39<00:00,  1.27it/s]
100%|████████████████████████████████████████████████████████████████| 50/50 [00:39<00:00,  1.28it/s]
Traceback (most recent call last):

**Comment by larini** [comment]
This project only works with nvidia graphic cards?
I have a Radeon rx 6950 xt.

**Comment by staoxiao** [comment]
@larini , sorry, the code only supports NVIDIA CUDA. We are short-staffed and cannot support more machines at the moment.

**Comment by kutoman** [comment]
> okay i fixed this problem by runing
> 
> conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia

I have tried that after a clean install. Now the early "service disconnected" console log does not appear anymore. But still, the app does not start, and my 16GB RAM gets completely blocked and my system gets almost unresponsive.
I'm running it through pinokio and I haven't had such issue before with the other apps.

**Comment by fbauer-kunbus** [comment]
I will uninstall this now. I've got six other similar AI installations with conda/venv environment running here without problems where I didn't have to make such manual adjustments. As long as the developers don't do their homework on this installation, I won't use and won't recommend it.

**Comment by Bouhoum** [comment]
I have solved the issue, but I don't remember how since I have tried many things, first thing I did downgrade cuda toolkit from 12.5.x to 12.1.1, also I found out that I had pytorchCPU and not pytorch-cuda (make sure it is installed), and pytorch-cuda apparently wouldn't want to install unless I uninstall pytorch CPU one. 
`conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia` this didn't work until I uninstalled pytorch CPU 

make sure you have all of these installed, maybe use a conda venv or py venv so u wont have libraries conflicts.

**Comment by jgardet** [comment]
I confirm that on my CPU only laptop the error "NameError: name 'is_torch_npu_available' is not defined. Did you mean: 'is_torch_xla_available'?" appears on the lastest code at time of writing. I'll try with a RTX 4080 tomorrow to see what happens.
