### ISSUE TITLE
Output image error

### ISSUE THREAD

**Issue by vcoopers** [VectorSpaceLab/OmniGen#70]
Im getting output image error:

Traceback (most recent call last):
  File "C:\cp\OmniGen\venv\lib\site-packages\gradio\queueing.py", line 624, in process_events
    response = await route_utils.call_process_api(
  File "C:\cp\OmniGen\venv\lib\site-packages\gradio\route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\cp\OmniGen\venv\lib\site-packages\gradio\blocks.py", line 2018, in process_api
    result = await self.call_function(
  File "C:\cp\OmniGen\venv\lib\site-packages\gradio\blocks.py", line 1567, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\cp\OmniGen\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\cp\OmniGen\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "C:\cp\OmniGen\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "C:\cp\OmniGen\venv\lib\site-packages\gradio\utils.py", line 846, in wrapper
    response = f(*args, **kwargs)
  File "C:\cp\OmniGen\app.py", line 22, in generate_image
    output = pipe(
  File "C:\cp\OmniGen\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\cp\OmniGen\OmniGen\pipeline.py", line 278, in __call__
    samples = scheduler(latents, func, model_kwargs, use_kv_cache=use_kv_cache, offload_kv_cache=offload_kv_cache)
  File "C:\cp\OmniGen\OmniGen\scheduler.py", line 156, in __call__
    cache = [OmniGenCache(num_tokens_for_img, offload_kv_cache) for _ in range(len(model_kwargs['input_ids']))] if use_kv_cache else None
  File "C:\cp\OmniGen\OmniGen\scheduler.py", line 156, in <listcomp>
    cache = [OmniGenCache(num_tokens_for_img, offload_kv_cache) for _ in range(len(model_kwargs['input_ids']))] if use_kv_cache else None
  File "C:\cp\OmniGen\OmniGen\scheduler.py", line 14, in __init__
    raise RuntimeError("OffloadedCache can only be used with a GPU")
RuntimeError: OffloadedCache can only be used with a GPU

Fyi, I have a laptop with 4070 with 8gb vram.

**Comment by fbauer-kunbus** [comment]
Same here, with a 16GB 4090 Laptop GPU. 
Look like OmniGen doesn't even seem to try to use the GPU on my system - while multiple other AI installations don't encounter any problems.

**Comment by MoRgllgRoM** [comment]
Same here, with 3080ti 12GB desktop.

**Comment by staoxiao** [comment]
same error: https://github.com/VectorSpaceLab/OmniGen/issues/67

The issue is that no GPU device is detected, i.e., torch.cuda.is_available()=False. This could be due to an environment issue, such as PyTorch not being installed, or a mismatch between the PyTorch and CUDA versions. If the torch version is not suitable for your device, you can use a lower version, e.g., 2.1
You can print torch.cuda.is_available() in the same environment to check if the GPU is correctly recognized.

I modified the setup.py file to relax the version requirement for torch from ==2.3.1 to <2.5 (because there is a bug in torch 2.5). This might help to construct a correct environment.
