### ISSUE TITLE
I am getting Error OffloadedCache can only be used with a GPU

### ISSUE THREAD

**Issue by chnisar515** [VectorSpaceLab/OmniGen#73]
Hello Experts,
i have installed fresh copy of OmniGen using conda env and i have completed all the steps successfully after that when i try to launch OmniGen with this command `python app.py` the i got this output which is below.

`Fetching 10 files: 100%|███████████████████████████████████████████████████████████████████████| 10/10 [00:00<?, ?it/s]
Loading safetensors
INFO: Could not find files for the given pattern(s).
* Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.`

and then i click on the url `http://127.0.0.1:7860` and successfully open the OmniGen in gradio but when i type any prompt and try to generate the image i got this error output.

> Traceback (most recent call last):
  File "C:\Users\chnis\anaconda3\envs\omnigen01\lib\site-packages\gradio\queueing.py", line 624, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\chnis\anaconda3\envs\omnigen01\lib\site-packages\gradio\route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\chnis\anaconda3\envs\omnigen01\lib\site-packages\gradio\blocks.py", line 2018, in process_api
    result = await self.call_function(
  File "C:\Users\chnis\anaconda3\envs\omnigen01\lib\site-packages\gradio\blocks.py", line 1567, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\Users\chnis\anaconda3\envs\omnigen01\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\chnis\anaconda3\envs\omnigen01\lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "C:\Users\chnis\anaconda3\envs\omnigen01\lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "C:\Users\chnis\anaconda3\envs\omnigen01\lib\site-packages\gradio\utils.py", line 846, in wrapper
    response = f(*args, **kwargs)
  File "E:\My AI\omnigen\OmniGen\app.py", line 22, in generate_image
    output = pipe(
  File "C:\Users\chnis\anaconda3\envs\omnigen01\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\My AI\omnigen\OmniGen\OmniGen\pipeline.py", line 278, in __call__
    samples = scheduler(latents, func, model_kwargs, use_kv_cache=use_kv_cache, offload_kv_cache=offload_kv_cache)
  File "E:\My AI\omnigen\OmniGen\OmniGen\scheduler.py", line 156, in __call__
    cache = [OmniGenCache(num_tokens_for_img, offload_kv_cache) for _ in range(len(model_kwargs['input_ids']))] if use_kv_cache else None
  File "E:\My AI\omnigen\OmniGen\OmniGen\scheduler.py", line 156, in <listcomp>
    cache = [OmniGenCache(num_tokens_for_img, offload_kv_cache) for _ in range(len(model_kwargs['input_ids']))] if use_kv_cache else None
  File "E:\My AI\omnigen\OmniGen\OmniGen\scheduler.py", line 14, in __init__
    raise RuntimeError("OffloadedCache can only be used with a GPU")
RuntimeError: OffloadedCache can only be used with a GPU

**Comment by TigerFox57** [comment]
I have the same error, also using a conda environment.

**Comment by eizoxx** [comment]
Got the same error, solved it, by installing: 
`pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118` 
You have to replace cu118 with the cuda version you have installed.

**Comment by svyatokha** [comment]
> Got the same error, solved it, by installing: `pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118` You have to replace cu118 with the cuda version you have installed.  
worked for me) Thanks)

**Comment by chnisar515** [comment]
> Got the same error, solved it, by installing: `pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118` You have to replace cu118 with the cuda version you have installed.

Thank you, it worked for me.

**Comment by CyrilH187** [comment]
So I had the same issue. And I'm a complete noob at this, so I thought perhaps this can help another complete noob who ran into the same problem. For me,
 
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

didn't fix the problem. I still got the Offload cache can only be used with GPU error.

But everything installed correctly, however nvcc --version was returning that there was no such thing as cuda. So I found a fix on some stackoverflow post, the wizard there said that conda installs cuda differently and doesn't get the whole package so to speak so nvcc not giving a version is perfectly normal. 
Try:
conda install cuda -c nvidia

Which will install whatever is missing. That in addition to the pip torch install fixed it for me. Now everything works.

**Comment by Manda69-bit** [comment]
After losing half of day to try all possible versions of modules i made it to work 100%
So here are my tips:
1) You want to run code in virtual environment , python version 3.11
From my tests with different version you won't be able install required module versions 
2) Looks like you really want Cuda 11.8 because  if i'm not wrong new cuda version want python 3.12 and that wont let you install older modules
3) As in requirements says  you want torch 2.3.1 
# CUDA 11.8 +torch 2.31 code bellow:

conda install pytorch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 pytorch-cuda=11.8 -c pytorch -c nvidia

4) Check your requirements.txt  for all modul versions , and check what you have installed
Ex. You want   numpy==1.26.3 and package before installed me ver 2+, of course I had some issues 

Hope it helps,  so hours won't be lost for nothing.

**Comment by RodgerE1** [comment]
> After losing half of day to try all possible versions of modules i made it to work 100% So here are my tips:
> 
> 1. You want to run code in virtual environment , python version 3.11
>    From my tests with different version you won't be able install required module versions
> 2. Looks like you really want Cuda 11.8 because  if i'm not wrong new cuda version want python 3.12 and that wont let you install older modules
> 3. As in requirements says  you want torch 2.3.1
> 
> # CUDA 11.8 +torch 2.31 code bellow:
> conda install pytorch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 pytorch-cuda=11.8 -c pytorch -c nvidia
> 
> 4. Check your requirements.txt  for all modul versions , and check what you have installed
>    Ex. You want   numpy==1.26.3 and package before installed me ver 2+, of course I had some issues
> 
> Hope it helps, so hours won't be lost for nothing.

Worked for me!

**Comment by siglr** [comment]
Thank you! It fixed it for me!

**Comment by Yau0608** [comment]
> After losing half of day to try all possible versions of modules i made it to work 100% So here are my tips:
> 
> 1. You want to run code in virtual environment , python version 3.11
>    From my tests with different version you won't be able install required module versions
> 2. Looks like you really want Cuda 11.8 because  if i'm not wrong new cuda version want python 3.12 and that wont let you install older modules
> 3. As in requirements says  you want torch 2.3.1
> 
> # CUDA 11.8 +torch 2.31 code bellow:
> conda install pytorch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 pytorch-cuda=11.8 -c pytorch -c nvidia
> 
> 4. Check your requirements.txt  for all modul versions , and check what you have installed
>    Ex. You want   numpy==1.26.3 and package before installed me ver 2+, of course I had some issues
> 
> Hope it helps, so hours won't be lost for nothing.

Thank you so much, this really works!

**Comment by 8Ennui** [comment]
> After losing half of day to try all possible versions of modules i made it to work 100% So here are my tips:
> 
> 1. You want to run code in virtual environment , python version 3.11
>    From my tests with different version you won't be able install required module versions
> 2. Looks like you really want Cuda 11.8 because  if i'm not wrong new cuda version want python 3.12 and that wont let you install older modules
> 3. As in requirements says  you want torch 2.3.1
> 
> # CUDA 11.8 +torch 2.31 code bellow:
> conda install pytorch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 pytorch-cuda=11.8 -c pytorch -c nvidia
> 
> 4. Check your requirements.txt  for all modul versions , and check what you have installed
>    Ex. You want   numpy==1.26.3 and package before installed me ver 2+, of course I had some issues
> 
> Hope it helps, so hours won't be lost for nothing.

THIS WORKS!!!

**Comment by albertlt** [comment]
> After losing half of day to try all possible versions of modules i made it to work 100% So here are my tips:
> 
> 1. You want to run code in virtual environment , python version 3.11
>    From my tests with different version you won't be able install required module versions
> 2. Looks like you really want Cuda 11.8 because  if i'm not wrong new cuda version want python 3.12 and that wont let you install older modules
> 3. As in requirements says  you want torch 2.3.1
> 
> # CUDA 11.8 +torch 2.31 code bellow:
> conda install pytorch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 pytorch-cuda=11.8 -c pytorch -c nvidia
> 
> 4. Check your requirements.txt  for all modul versions , and check what you have installed
>    Ex. You want   numpy==1.26.3 and package before installed me ver 2+, of course I had some issues
> 
> Hope it helps, so hours won't be lost for nothing.

Another noob here. I have the same issue.

First, I executed:
conda install pytorch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 pytorch-cuda=11.8 -c pytorch -c nvidia

outside of omnigen [ C:\OmniGen\ ] prompt using cmd prompt with admin privilege. All installed but I still get the following error:
No avaliable GPU, offload_kv_cache wiil be set to False, which will result in large memory usage and time cost when input multiple images!!!
Traceback (most recent call last):
  File "C:\Users\alber\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\queueing.py", line 624, in process_events
    response = await route_utils.call_process_api(

Second, I entered omnigen env [ (omnigen) C:\OmniGen\ ] prompt using cmd prompt with admin privilege. Execute again:
conda install pytorch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 pytorch-cuda=11.8 -c pytorch -c nvidia

After that, python app.py just crashed with many missing files error. I went back to square zero with:

1. conda deactivate
2. conda env remove -n omnigen
3. conda create -n omnigen
4. conda activate omnigen
5. pip install -e .
6. pip install gradio spaces
7. python app.py

Total noob here. Can someone please guide me?

**Comment by clevnumb** [comment]
> After losing half of day to try all possible versions of modules i made it to work 100% So here are my tips:
> 
>     1. You want to run code in virtual environment , python version 3.11
>        From my tests with different version you won't be able install required module versions
> 
>     2. Looks like you really want Cuda 11.8 because  if i'm not wrong new cuda version want python 3.12 and that wont let you install older modules
> 
>     3. As in requirements says  you want torch 2.3.1
> 
> 
> # CUDA 11.8 +torch 2.31 code bellow:
> 
> conda install pytorch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 pytorch-cuda=11.8 -c pytorch -c nvidia
> 
>     4. Check your requirements.txt  for all modul versions , and check what you have installed
>        Ex. You want   numpy==1.26.3 and package before installed me ver 2+, of course I had some issues
> 
> 
> Hope it helps, so hours won't be lost for nothing.

This worked for me as well! After running your longer conda install pytorch (etc) command, I ran: _pip install -r requirements. txt_   (obviously all in the Conda environment) and viola, it works now. Thank you!
