### ISSUE TITLE
RuntimeError: OffloadedCache can only be used with a GPU

### ISSUE THREAD

**Issue by TanvirHafiz** [VectorSpaceLab/OmniGen#89]
I have a 3090 with 24GB VRAM. i tried to geneate with 2 images and i get this error

Traceback (most recent call last):
  File "F:\OmniGen\venv\lib\site-packages\gradio\queueing.py", line 624, in process_events
    response = await route_utils.call_process_api(
  File "F:\OmniGen\venv\lib\site-packages\gradio\route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
  File "F:\OmniGen\venv\lib\site-packages\gradio\blocks.py", line 2018, in process_api
    result = await self.call_function(
  File "F:\OmniGen\venv\lib\site-packages\gradio\blocks.py", line 1567, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "F:\OmniGen\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "F:\OmniGen\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "F:\OmniGen\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "F:\OmniGen\venv\lib\site-packages\gradio\utils.py", line 846, in wrapper
    response = f(*args, **kwargs)
  File "F:\OmniGen\app.py", line 22, in generate_image
    output = pipe(
  File "F:\OmniGen\venv\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "F:\OmniGen\OmniGen\pipeline.py", line 278, in __call__
    samples = scheduler(latents, func, model_kwargs, use_kv_cache=use_kv_cache, offload_kv_cache=offload_kv_cache)
  File "F:\OmniGen\OmniGen\scheduler.py", line 156, in __call__
    cache = [OmniGenCache(num_tokens_for_img, offload_kv_cache) for _ in range(len(model_kwargs['input_ids']))] if use_kv_cache else None
  File "F:\OmniGen\OmniGen\scheduler.py", line 156, in <listcomp>
    cache = [OmniGenCache(num_tokens_for_img, offload_kv_cache) for _ in range(len(model_kwargs['input_ids']))] if use_kv_cache else None
  File "F:\OmniGen\OmniGen\scheduler.py", line 14, in __init__
    raise RuntimeError("OffloadedCache can only be used with a GPU")
RuntimeError: OffloadedCache can only be used with a GPU

What needs to be done?

**Comment by staoxiao** [comment]
This issue is caused by the GPU not being detected, usually due to an incomplete GPU environment setup. You can refer to the following solution: https://github.com/VectorSpaceLab/OmniGen/issues/67

**Comment by ialhabbal** [comment]
Got the same error, solved it, by installing:
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
You have to replace cu118 with the cuda version you have installed.
